# Configuração Anti-Veículo/Moto para Detecção de Pessoas
# Sistema para diferenciar pessoas de motos e outros veículos

# Validações de Altura e Proporção
height_validation:
  min_height_px: 140          # Altura mínima em pixels para ser pessoa
  max_height_px: 3000         # Altura máxima em pixels
  
  # Proporções anatômicas humanas RIGOROSAS
  min_aspect_ratio: 1.8       # Altura/largura mínima (pessoas são MUITO mais altas)
  max_aspect_ratio: 6.0       # Altura/largura máxima
  
  # Tamanhos mínimos
  min_width_px: 30            # Largura mínima em pixels
  min_height_px_small: 50     # Altura mínima em pixels para objetos pequenos

# Validações Anti-Veículo (MAIS RIGOROSAS)
vehicle_detection:
  # 🏍️ DETECÇÃO ESPECÍFICA DE MOTOS:
  motorcycle_threshold:
    min_ratio: 0.7            # Largura/altura mínima para ser considerado moto
    max_ratio: 1.3            # Largura/altura máxima para ser considerado moto
  
  # Formas retangulares (típicas de veículos)
  rectangular_threshold:
    min_ratio: 0.8            # Largura/altura mínima para ser considerado retangular
    max_ratio: 1.2            # Largura/altura máxima para ser considerado retangular
  
  # Veículos muito largos
  wide_vehicle_threshold: 1.5  # Largura/altura para detectar veículos largos
  
  # Objetos óbvios
  obvious_vehicle_threshold: 2.0  # Largura/altura para veículos extremamente largos

# Validação de Movimento
movement_validation:
  # Movimento linear vs orgânico
  linear_movement_threshold: 0.3  # std/mean para detectar movimento muito linear
  
  # Histórico de frames para análise
  min_frames_for_analysis: 3      # Frames mínimos para validar movimento
  max_history_frames: 10          # Frames máximos no histórico

# Thresholds de Confiança (AJUSTADOS PARA 0.25)
confidence_thresholds:
  high_confidence: 0.5        # Confiança alta = valida com filtros rigorosos
  medium_high_confidence: 0.4 # Confiança média-alta = valida com filtros médios
  medium_confidence: 0.25     # Confiança média = filtros rigorosos (AJUSTADO)
  low_confidence: 0.25        # Confiança baixa = rejeita (AJUSTADO)

# Logging e Debug
debug:
  enable_detailed_logs: true   # Logs detalhados de validação
  show_rejection_reasons: true # Mostra razões de rejeição
  log_movement_analysis: true  # Logs de análise de movimento
  log_vehicle_detection: true  # Logs específicos de detecção de veículos
